# For Code
face global value bright-blue
face global type bright-magenta
face global variable green
face global module cyan
face global function type
face global string bright-green
face global keyword magenta
face global operator yellow
face global attribute green
face global comment white
face global documentation comment
face global meta blue
face global builtin default+b

# For markup
face global title blue
face global header cyan
face global mono green
face global block magenta
face global link cyan
face global bullet cyan
face global list yellow

# builtin faces
face global Default default,default
face global PrimarySelection white,blue+fg
face global SecondarySelection black,blue+fg
face global PrimaryCursor black,white+fg
face global SecondaryCursor black,white+fg
face global PrimaryCursorEol black,cyan+fg
face global SecondaryCursorEol black,cyan+fg
face global LineNumbers default,default
face global LineNumberCursor default,default+r
face global MenuForeground bright-white,bright-black
face global MenuBackground white,black
face global MenuInfo cyan
face global Information black,yellow
face global Error black,red
face global DiagnosticError red
face global DiagnosticWarning yellow
face global StatusLine cyan,default
face global StatusLineMode yellow,default
face global StatusLineInfo blue,default
face global StatusLineValue green,default
face global StatusCursor black,cyan
face global Prompt yellow,default
face global MatchingChar default,default+b
face global Whitespace default,default+fd
face global BufferPadding blue,default

# Tree-sitter
set-face global ts_attribute                    green
set-face global ts_comment                      white+i
set-face global ts_comment_unused               white+is
set-face global ts_conceal                      magenta+i
set-face global ts_constant                     yellow
set-face global ts_constant_builtin_boolean     red
set-face global ts_constant_character           yellow
set-face global ts_constant_macro               magenta
set-face global ts_constructor                  blue
set-face global ts_diff_plus                    green
set-face global ts_diff_minus                   red
set-face global ts_diff_delta                   blue
set-face global ts_diff_delta_moved             magenta
set-face global ts_error                        red+b
set-face global ts_function                     blue
set-face global ts_function_builtin             blue+i
set-face global ts_function_macro               magenta
set-face global ts_hint                         blue+b
set-face global ts_info                         cyan+b
set-face global ts_keyword                      magenta
set-face global ts_keyword_conditional          magenta+i
set-face global ts_keyword_control_conditional  magenta+i
set-face global ts_keyword_control_directive    magenta+i
set-face global ts_keyword_control_import       magenta+i
set-face global ts_keyword_directive            magenta+i
set-face global ts_label                        blue+i
set-face global ts_markup_bold                  yellow+b
set-face global ts_markup_heading               red
set-face global ts_markup_heading_1             red
set-face global ts_markup_heading_2             magenta
set-face global ts_markup_heading_3             green
set-face global ts_markup_heading_4             yellow
set-face global ts_markup_heading_5             magenta
set-face global ts_markup_heading_6             cyan
set-face global ts_markup_heading_marker        yellow+b
set-face global ts_markup_italic                magenta+i
set-face global ts_markup_list_checked          green
set-face global ts_markup_list_numbered         blue+i
set-face global ts_markup_list_unchecked        cyan
set-face global ts_markup_list_unnumbered       magenta
set-face global ts_markup_link_label            blue
set-face global ts_markup_link_url              cyan+u
set-face global ts_markup_link_uri              cyan+u
set-face global ts_markup_link_text             blue
set-face global ts_markup_quote                 bright-black
set-face global ts_markup_raw                   green
set-face global ts_markup_strikethrough         bright-black+s
set-face global ts_namespace                    blue+i
set-face global ts_operator                     blue
set-face global ts_property                     blue
set-face global ts_punctuation                  bright-black
set-face global ts_punctuation_special          blue
set-face global ts_special                      blue
set-face global ts_spell                        magenta
set-face global ts_string                       green
set-face global ts_string_regex                 yellow
set-face global ts_string_regexp                yellow
set-face global ts_string_escape                magenta
set-face global ts_string_special               blue
set-face global ts_string_special_path          green
set-face global ts_string_special_symbol        magenta
set-face global ts_string_symbol                red
set-face global ts_tag                          magenta
set-face global ts_tag_error                    red
set-face global ts_text                         default
set-face global ts_text_title                   magenta
set-face global ts_type                         yellow
set-face global ts_type_enum_variant            blue
set-face global ts_type_enum_variant_builtin    blue+i
set-face global ts_variable                     default
set-face global ts_variable_builtin             red
set-face global ts_variable_other_member        cyan
set-face global ts_variable_parameter           yellow+i
set-face global ts_warning                      yellow+b
